import {
  apiGetAppointments,
  apiPostAppointment,
  apiGetAppointmentById,
  apiPutAppointmentById,
  apiDeleteAppointmentById,
} from "./apiAppointment";

import {
  apiGetUsersList,
  apiGetUsersListById,
  apiPostUsersRegister,
  apiPostUsersConfirm,
  apiGetUsersLogin,
  apiGetUsersForgotPassword,
  apiPutUsersById,
  apiGetUserByEmail,
} from "./apiUser";

import {
  apiGetCases,
  apiGetCasesById,
  apiPostCases,
  apiPatchCaseById,
  apiPutCasesById,
  apiPatchCasesByIdAssign,
  apiPatchCasesByIdDecline,
  apiPatchCasesByIdAccept,
  apiPatchCasesByIdReady,
  apiPatchCasesByIdQuote,
  apiPatchCasesByIdClose,
  apiGetCasesToDo,
  apiGetCoordinates,
  apiGetCasesItems,
  apiGetCasesItemByRoom,
} from "./apiCase";

export {
  apiGetAppointments,
  apiPostAppointment,
  apiGetAppointmentById,
  apiPutAppointmentById,
  apiDeleteAppointmentById,
  apiGetCases,
  apiGetCasesById,
  apiPostCases,
  apiPatchCaseById,
  apiPutCasesById,
  apiPatchCasesByIdAssign,
  apiPatchCasesByIdDecline,
  apiPatchCasesByIdAccept,
  apiPatchCasesByIdReady,
  apiPatchCasesByIdQuote,
  apiPatchCasesByIdClose,
  apiGetUsersList,
  apiGetUserByEmail,
  apiGetUsersListById,
  apiPostUsersRegister,
  apiPostUsersConfirm,
  apiGetUsersLogin,
  apiGetUsersForgotPassword,
  apiPutUsersById,
  apiGetCasesToDo,
  apiGetCoordinates,
  apiGetCasesItems,
  apiGetCasesItemByRoom,
};
